<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC9TB4aA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC9TB4aA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC9TB4aA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC9TB4aA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC9TB4aA\App_KernelDevDebugContainer([
    'container.build_hash' => 'C9TB4aA',
    'container.build_id' => '9d678aba',
    'container.build_time' => 1744817270,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC9TB4aA');
